---
- hosts: localhost
  connection: local
  environment:
    http_proxy: http://172.16.1.5:8080
    https_proxy: http://172.16.1.5:8080
  tasks:
   - name: Install Apache2
     apt: pkg=apache2 state=installed update_cache=true
   - name: Start Apache2
     service: name=nginx state=started
   - name: Install Git
     apt: pkg=git state=installed update_cache=true
   
