---
- hosts: localhost
  connection: local
  tasks:
  - name: Add user
    user:
      name: plop
      password: "$6$rounds=4096$PbpT11Ec$xlubHkto9wh7MTVAuyu5VPXsz2YGUsSHD6MvvCa7BAzOGblcWsYvsflpW/qdceThrxm1z9C41YEN1tWgordyj0"
      groups: sudo

  - name: Remove apt lists files
    command: rm -rf /var/lib/apt/*
    sudo: yes

  - name: Remove apt cache files
    command: apt-get clean
    sudo: yes
    
  - name: Clean apt
    command: apt-get update
    sudo: yes
      
  - name: Install Apache2
    apt:
      pkg: apache2
      state: installed
      update_cache: true 
    environment:
      http_proxy: http://172.16.1.5:8080
      https_proxy: http://172.16.1.5:8080

  - name: Start Apache2
    service: 
      name: apache2
      state: started

  - name: Install Git
    apt:
      pkg: git
      state: installed
    environment:
      http_proxy: http://172.16.1.5:8080
      https_proxy: http://172.16.1.5:8080

  - name: Create directory 
    file:
      path: /var/www/html/website/
      state: directory

  - name: Clone website code
    git:
      repo: https://github.com/sl4shme/roche_lorem.git
      dest: /var/www/html/website/
    environment:
      http_proxy: http://172.16.1.5:8080
      https_proxy: http://172.16.1.5:8080
